version: '3'
services: 
  app:
    build: .
    ports:
      - 3000:3000
    environment: 
      NODE_ENV: dev

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senaidev
      MYSQL_USER: senai
      MYSQL_PASSWORD: senai
    ports:
      - 3306:3306
